# Ví dụ đơn giản - Bạn nên dùng manifest chính thức từ Tyk cho môi trường production
---
# Deployment cho Tyk Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyk-gateway
  namespace: tyk # Giả sử bạn deploy vào namespace 'tyk'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyk-gateway
  template:
    metadata:
      labels:
        app: tyk-gateway
    spec:
      containers:
      - name: tyk-gateway
        image: tykio/tyk-gateway:v5.3.0
        ports:
        - containerPort: 8080
        env:
        - name: TYK_GW_SECRET
          value: "your-secret-here"
---
# Service để expose Tyk Gateway
apiVersion: v1
kind: Service
metadata:
  name: tyk-gateway-service
  namespace: tyk
spec:
  type: LoadBalancer
  selector:
    app: tyk-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080