apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: todo-app
spec:
  serviceName: auth-db
  replicas: 1
  selector:
    matchLabels:
      app: auth-mysql-db
  template:
    metadata:
      labels:
        app: auth-mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: auth-db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: auth-db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: auth-db-password
        volumeMounts:
        - name: auth-db-data
          mountPath: /var/lib/mysql
        - name: auth-db-init
          mountPath: /docker-entrypoint-initdb.d
        securityContext:
          runAsUser: 999
          runAsGroup: 999
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: auth-db-init
        configMap:
          name: auth-db-config
      - name: auth-db-data # <-- Đã có trong bản gốc
        persistentVolumeClaim:
          claimName: auth-db-data # <-- Đã có trong bản gốc
  volumeClaimTemplates:
  - metadata:
      name: auth-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
# Profile Database StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: profile-db
  namespace: todo-app
spec:
  serviceName: profile-db
  replicas: 1
  selector:
    matchLabels:
      app: profile-mysql-db
  template:
    metadata:
      labels:
        app: profile-mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-password
        volumeMounts:
        - name: profile-db-data
          mountPath: /var/lib/mysql
        - name: profile-db-init
          mountPath: /docker-entrypoint-initdb.d
        securityContext:
          runAsUser: 999
          runAsGroup: 999
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: profile-db-init
        configMap:
          name: profile-db-config
      - name: profile-db-data # <-- Đã có trong bản gốc
        persistentVolumeClaim:
          claimName: profile-db-data # <-- Đã có trong bản gốc
  volumeClaimTemplates:
  - metadata:
      name: profile-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
# Task Database StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: task-db
  namespace: todo-app
spec:
  serviceName: task-db
  replicas: 1
  selector:
    matchLabels:
      app: task-mysql-db
  template:
    metadata:
      labels:
        app: task-mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: task-db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: task-db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: task-db-password
        volumeMounts:
        - name: task-db-data
          mountPath: /var/lib/mysql
        - name: task-db-init
          mountPath: /docker-entrypoint-initdb.d
        securityContext:
          runAsUser: 999
          runAsGroup: 999
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: task-db-init
        configMap:
          name: task-db-config
      - name: task-db-data
        persistentVolumeClaim:
          claimName: task-db-data
  volumeClaimTemplates:
  - metadata:
      name: task-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: todo-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: auth-mysql-db
---
apiVersion: v1
kind: Service
metadata:
  name: profile-db
  namespace: todo-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: profile-mysql-db
---
apiVersion: v1
kind: Service
metadata:
  name: task-db
  namespace: todo-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: task-mysql-db