apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: todo-app
spec:
  serviceName: auth-db
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: auth-db-name # Giả định bạn có key này trong db-secrets
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: auth-db-user # Giả định bạn có key này trong db-secrets
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: auth-db-password
        volumeMounts:
        - name: auth-db-data
          mountPath: /var/lib/mysql
        - name: auth-db-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: auth-db-init
        configMap:
          name: auth-db-config
  volumeClaimTemplates:
  - metadata:
      name: auth-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
# Profile Database StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: profile-db
  namespace: todo-app
spec:
  serviceName: profile-db
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-name # Giả định bạn có key này trong db-secrets
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-user # Giả định bạn có key này trong db-secrets
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-password
        volumeMounts:
        - name: profile-db-data
          mountPath: /var/lib/mysql
        - name: profile-db-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: profile-db-init
        configMap:
          name: profile-db-config
  volumeClaimTemplates:
  - metadata:
      name: profile-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
# Task Database StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: task-db
  namespace: todo-app
spec:
  serviceName: task-db
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: task-db-name # Giả định bạn có key này trong db-secrets
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: task-db-user # Giả định bạn có key này trong db-secrets
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: task-db-password
        volumeMounts:
        - name: task-db-data
          mountPath: /var/lib/mysql
        - name: task-db-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: task-db-init
        configMap:
          name: task-db-config
  volumeClaimTemplates:
  - metadata:
      name: task-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: todo-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-db
---
apiVersion: v1
kind: Service
metadata:
  name: profile-db
  namespace: todo-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-db
---
apiVersion: v1
kind: Service
metadata:
  name: task-db
  namespace: todo-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-db