apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: auth-service-api
  namespace: todo-app
spec:
  name: Auth Service
  api_id: auth-service
  org_id: "1"
  use_keyless: true
  proxy:
    listen_path: /auth/
    target_url: http://auth-service:3100
    strip_listen_path: true
  active: true
  version_data:
    not_versioned: true
    default_version: "Default"
    versions:
      Default:
        name: "Default"
        use_extended_paths: true