apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: todo-app
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: phihocnguyen123/auth-service:${env.BUILD_NUMBER}
        ports:
        - containerPort: 3100
        env:
        - name: DB_HOST
          value: auth-db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: auth-db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: auth-db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: auth-db-name
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: todo-app
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100