apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service-deployment
  namespace: todo-app
  labels:
    app: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: phihocnguyen123/task-service:${env.BUILD_NUMBER}
        ports:
        - containerPort: 3300
        env:
        # Các biến môi trường cá nhân để lấy thông tin từ secrets
        # Các biến này sẽ được sử dụng để xây dựng chuỗi DB_DSN
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: task-db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: task-db-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: task-db-name
        command: ["/bin/sh", "-c"]
        args:
          - export DB_DSN="${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(task-db:3306)/${MYSQL_DATABASE}?charset=utf8mb4&parseTime=True&loc=Local";
            exec /app
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: todo-app
spec:
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300