apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service-deployment
  labels:
    app: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: phihocnguyen123/task-service:${env.BUILD_NUMBER}
        ports:
        - containerPort: 3300
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300