apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: todo-app
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: phihocnguyen123/user-service:${env.BUILD_NUMBER}
        ports:
        - containerPort: 3200
        env:
        - name: DB_HOST
          value: profile-db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: profile-db-name
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: todo-app
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200